const services=[['Residential Cleaning','Fresh, detailed cleaning for homes of every size.'],['Commercial Cleaning','Professional spaces that look polished and welcoming.'],['Deep Cleaning','A more thorough reset for kitchens, baths, and living areas.'],['Move-In / Move-Out','Start or finish a move with a spotless space.'],['Recurring Cleaning','Flexible weekly, biweekly, or monthly service.'],['Post-Construction','Detailed cleanup after renovations and construction.']];
function Brand(){return <a href="#home" className="brand" aria-label="Anderson Cleaning Services"><span className="brandMark">A</span><span className="brandText">ANDERSON <b>CLEANING SERVICES</b></span></a>}
export default function Home(){return <main>
<header className="nav"><Brand/><nav><a href="#services">Services</a><a href="#difference">About</a><a href="#quote">Contact</a><a href="#careers">Careers</a></nav><a className="btn small" href="#quote">Get a Free Quote</a></header>
<section id="home" className="hero"><div className="heroBg"/><div className="heroContent"><span className="eyebrow">CLEAN SPACES. HEALTHY PLACES.</span><h1>Professional cleaning services you can trust.</h1><p>Reliable, detailed, and affordable cleaning for homes and businesses throughout Palmdale and surrounding communities.</p><div className="actions"><a className="btn" href="#quote">Get a Free Quote</a><a className="btn ghost" href="#services">Explore Services</a></div><div className="trust"><span>✓ Detail-focused</span><span>✓ Flexible scheduling</span><span>✓ Local service</span></div></div><div className="heroVisual"><div className="visualGlow"/><div className="visualCard"><span>ANDERSON</span><strong>Cleaning<br/>Services</strong><i>Professional • Reliable • Local</i></div></div><div className="script">A cleaner home<br/>is a happier home</div></section>
<section className="intro"><span className="eyebrow blue">THE ANDERSON DIFFERENCE</span><h2>A cleaner space, without the hassle.</h2><p>We combine dependable service, thoughtful details, and a professional finish so you can spend less time cleaning and more time enjoying your space.</p></section>
<section id="services" className="services"><div className="sectionHead"><div><span className="eyebrow blue">WHAT WE DO</span><h2>Cleaning that fits your life.</h2></div><p>Choose a service or request a customized plan built around your needs.</p></div><div className="grid">{services.map(([title,desc],i)=><article className="card" key={title}><div className="icon">{String(i+1).padStart(2,'0')}</div><h3>{title}</h3><p>{desc}</p><a href="#quote">Learn more →</a></article>)}</div></section>
<section id="difference" className="difference"><div className="differenceVisual"><div className="cleanScene"><span>DETAILED</span><strong>FROM TOP<br/>TO BOTTOM</strong><small>THE ANDERSON STANDARD</small></div></div><div className="differenceCopy"><span className="eyebrow blue">WHY ANDERSON</span><h2>Professional results with a personal standard.</h2><p>From sparkling kitchens to refreshed living spaces, our approach is simple: show up prepared, respect your space, and leave every detail better than we found it.</p><div className="stats"><div><strong>6</strong><span>Core services</span></div><div><strong>100%</strong><span>Detail focused</span></div><div><strong>1</strong><span>Local team</span></div></div></div></section>
<section id="quote" className="quote"><div><span className="eyebrow">READY FOR A CLEANER SPACE?</span><h2>Let’s make your next clean the easiest one yet.</h2><p>Tell us what you need and we’ll help you choose the right service.</p></div><form action="mailto:info@andersoncleaningservices.com" method="post" encType="text/plain"><input name="name" placeholder="Your name" required/><input name="email" type="email" placeholder="Email address" required/><input name="service" placeholder="Service needed"/><textarea name="message" placeholder="Tell us about your space" rows={4}/><button className="btn" type="submit">Request a Quote</button></form></section>
<section id="careers" className="careers"><span className="eyebrow blue">JOIN THE TEAM</span><h2>Looking for a dependable cleaning career?</h2><p>Explore opportunities with Anderson Cleaning Services.</p><a className="btn" href="mailto:careers@andersoncleaningservices.com">Apply for a Position</a></section>
<footer><Brand/><div><a href="#home">Home</a><a href="#services">Services</a><a href="#difference">About</a><a href="#quote">Contact</a><a href="#careers">Careers</a></div><p>© 2026 Anderson Cleaning Services. All rights reserved.</p></footer>
</main>}